sudo: false
language: java
jdk: oraclejdk8
script: mvn clean package
before_deploy: npm install -g now
deploy:
- provider: script
  script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  skip_cleanup: true
  on:
    master: true
env:
  global:
    secure: SsPu4JmgktLCbic2ljz9pRIafDZbjUkmjPCwRvbqsbpWB2iUx8z7jSh2OuLJdLKBeOifXSdX4a9IGoylPEXZ7tuuCQLFRgQVdiW3qAOP5Tgqwsvh76gBPxeZLXO1bQqp9icP2jzaNqZ88zNAqPCJ/lnMneaFyhPa8rlxGzrb9XMajrrh3y1gTxvGpNAE6KzRSvBq6/BoN7iLx3UNOVNgowQYqktLxzaOZOY4WSXF+jPplfQ0y0M+cprWs/c4nyF6aHJtU/J81qLkbhkNK1PhaYfb6SV/7YwX64sxLc1B2oq2BX+60txZWECvNKOI8gwdzxY448IU1JS5Dokq7cH/WH4zTkB6KqlmccMhfdfgCiPfuRqcZWU1szuweF7oXfqjBOP6m0zTVq+Jqq5f8//1HNyJIv4fNnmxVMvwe73IBH8bGYzDPEwI06nsvEt1MAa/T23ZYuKQnjyh3BUhBdELkO/+z+UbOmCXVR+HhOQAa5GqL3c2EfAronPlGp9vMMD+twGeuFFn5gUI4vJuQx5iPXO0+MdMYVrPgwN9B9r0FV/okxqVyREEW7tR5R8at+I4g+xcqz22n1Td4wlY8VhRQTmsDYxQ9S4Y/JlOIEyuWnuaf8HgoGck39Sz/g8YjlTAzTDXgqKzdvN97uG9qS7HdrixsUddqxREafsLNccfbV8=
